- id: ash-pre-commit
  name: ASH Pre Commit Scan
  entry: powershell.exe -NoProfile -Command "Remove-Item -Recurse -Force .ash -ErrorAction SilentlyContinue; mkdir -Force .ash\\ash_output | Out-Null; ash --mode local"
  language: system
  stages: [pre-commit]

- id: ash-pre-push
  name: ASH Pre Push Scan
  entry: powershell.exe -NoProfile -Command "Remove-Item -Recurse -Force .ash -ErrorAction SilentlyContinue; mkdir -Force .ash\\ash_output | Out-Null; ash --mode local"
  language: system
  stages: [pre-push]
